export const sampleContacts = [
  // {
  //   id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  //   firstName: "John",
  //   lastName: "Doe",
  //   email: "john.doe@example.com",
  //   phone: "1234567890",
  //   company: "Tech Solutions",
  //   jobTitle: "Software Engineer",
  // },
  {
    id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "0987654321",
    company: "InnovateX",
    jobTitle: "Product Manager",
  },
  // {
  //   id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  //   firstName: "Alice",
  //   lastName: "Johnson",
  //   email: "alice.johnson@example.com",
  //   phone: "1122334455",
  //   company: "Marketing Pro",
  //   jobTitle: "Marketing Specialist",
  // },
  // {
  //   id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  //   firstName: "Bob",
  //   lastName: "Brown",
  //   email: "bob.brown@example.com",
  //   phone: "2233445566",
  //   company: "BuildIt Inc.",
  //   jobTitle: "Construction Manager",
  // },
  // {
  //   id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  //   firstName: "Charlie",
  //   lastName: "Davis",
  //   email: "charlie.davis@example.com",
  //   phone: "3344556677",
  //   company: "Finance World",
  //   jobTitle: "Financial Analyst",
  // },
  // {
  //   id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  //   firstName: "Diana",
  //   lastName: "Miller",
  //   email: "diana.miller@example.com",
  //   phone: "4455667788",
  //   company: "HealthPlus",
  //   jobTitle: "Nurse",
  // },
  // {
  //   id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  //   firstName: "Ethan",
  //   lastName: "Wilson",
  //   email: "ethan.wilson@example.com",
  //   phone: "5566778899",
  //   company: "Green Energy",
  //   jobTitle: "Environmental Scientist",
  // },
  // {
  //   id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  //   firstName: "Fiona",
  //   lastName: "Clark",
  //   email: "fiona.clark@example.com",
  //   phone: "6677889900",
  //   company: "EduTech",
  //   jobTitle: "Educational Consultant",
  // },
  // {
  //   id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  //   firstName: "George",
  //   lastName: "Harris",
  //   email: "george.harris@example.com",
  //   phone: "7788990011",
  //   company: "Logistics Hub",
  //   jobTitle: "Logistics Coordinator",
  // },
  // {
  //   id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  //   firstName: "Hannah",
  //   lastName: "Walker",
  //   email: "hannah.walker@example.com",
  //   phone: "8899001122",
  //   company: "Design Studio",
  //   jobTitle: "Graphic Designer",
  // },
];

export const defaultValues = {
  firstName: "Yash",
  lastName: "Doe",
  email: "john.doe@example.com",
  phone: "1234567890",
  company: "Tech Solutions",
  jobTitle: "Software Engineer",
};
